apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sky
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Coflnet/kube_us.git
    targetRevision: HEAD
    path: sky
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sky
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
