apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dedup-dotnet
  namespace: kafka
  labels:
    app: kafka-dedup-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-dedup-dotnet
  template:
    metadata:
      labels:
        app: kafka-dedup-dotnet
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: kafka-dedup-dotnet
        image: registry.flou.dev/kafka-dedup-dotnet:b7b9e8e1-212d-4034-a2fd-ae414c91807e
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              key: kafka_host
              name: config
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: redis_host
              name: config
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: secret
        - name: SOURCE_TOPIC
          valueFrom:
            configMapKeyRef:
              key: source_topic
              name: config
        - name: TARGET_TOPIC
          valueFrom:
            configMapKeyRef:
              key: target_topic
              name: config
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              key: batch_size
              name: config
        - name: BATCH_WAIT_TIME
          valueFrom:
            configMapKeyRef:
              key: batch_wait_time
              name: config
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
