apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mail-notification-webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: mail-notification
    eventSourceName: mail-notification-eventsource
    eventName: mail-notification
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              namespace: argo
              generateName: build-mail-notification-
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              imagePullSecrets:
                - name: regcred
              entrypoint: build
              serviceAccountName: argo
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: secret
                secret:
                  secretName: secret
              templates:
              - name: build
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: build-container-image
                      template: build-kaniko-git
                    arguments:
                      parameters:
                      - name: app_repo
                        value: git://github.com/Flou21/mail-notification.git
                      - name: container_image
                        value: registry.flou21.de/mail-notification
                      - name: container_tag
                        value: latest
                      - name: sub_path 
                        value: .
                      - name: git_user
                        value: "Flou21"
                      - name: git_secret_name
                        value: github-secret
                      - name: git_secret_key
                        value: password
                      - name: branch
                        value: main