apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    name: cypress-tests-edge88
    namespace: argo
spec:
    serviceAccountName: argo-events-sa
    templates:
    - name: cypress-tests-edge88
      inputs:
        parameters:
          - name: git_repository
          - name: spec
          - name: cypress_base_url
      container:
        image: registry.flou.dev/cypress-runner:edge88
        imagePullPolicy: Always
        env:
        - name: CYPRESS_BASE_URL
          value: "{{inputs.parameters.cypress_base_url}}"
        resources:
          requests:
            memory: 2500Mi
            cpu: 3000m
        args:
        - /app
        - --repository="{{inputs.parameters.git_repository}}"
        - --branch="master"
        - --browser=edge
        - --spec="{{inputs.parameters.spec}}"