apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  namespace: observability
  name: jaeger
spec:
  strategy: allInOne # <1>
  storage:
    type: cassandra
    options: # <2>
      cassandra:
        servers: cassandra.cassandra.svc.cluster.local
        keyspace: jaeger_v1
        username: "cassandra"
        password: "Ds28melByL"
    cassandraCreateSchema: # <3>
      datacenter: "datacenter1"
      mode: "test"
