apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: stage-frontend-webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: sky-stage-frontend
    eventSourceName: sky-eventsource
    eventName: sky-stage-frontend
    filters: 
      data:
      - path: body.ref
        type: string
        value:
          - refs/heads/develop
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              namespace: argo
              generateName: build-stage-frontend-sky-
              labels:
                workflows.argoproj.io/archive-strategy: "true"
            spec:
              entrypoint: build
              serviceAccountName: argo
              retryStrategy:
                    limit: 10
                    retryPolicy: "Always"
                    backoff:
                      duration: "1"
                      factor: 2
                      maxDuration: "30m"
              imagePullSecrets:
                - name: regcred
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: secret
                secret:
                  secretName: secret
              - name: sky-argo-secret
                secret:
                  secretName: sky-argo-secret
              templates:
              - name: build
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: build-container-image
                      template: build-kaniko-git
                    arguments:
                      parameters:
                      - name: app_repo
                        value: git://github.com/Coflnet/hypixel-react.git
                      - name: branch
                        value: develop
                      - name: container_image
                        value: registry.flou.dev/sky-stage-frontend
                      - name: container_tag
                        value: "{{workflow.uid}}"
                      - name: sub_path 
                        value: .
                      - name: git_user
                        value: "Flou21"
                      - name: git_secret_name
                        value: github-secret
                      - name: git_secret_key
                        value: password

                  - name: promote-frontend
                    templateRef:
                      name: promote
                      template: promote
                    arguments:
                      parameters:
                      - name: tag
                        value: "{{workflow.uid}}"
                      - name: git_user
                        value: "Flou21"
                      - name: git_secret_name
                        value: github-secret
                      - name: git_secret_key
                        value: password
                      - name: repo_url
                        value: "github.com/Coflnet/kube.git"
                      - name: image_name
                        value: registry.flou.dev\/sky-stage-frontend
                      - name: k8s_file
                        value: ./sky/stage-frontend.yaml
                      - name: message
                        value: "[CI] sky stage frontend - version bump {{workflow.uid}}"
                    dependencies: [build]

                  - name: argo-sync
                    templateRef: 
                      name: argo-sync
                      template: argo-sync
                    arguments:
                      parameters:
                        - name: app_name
                          value: sky
                        - name: argo_server_secret_name
                          value : sky-argo-secret
                        - name: argo_server_secret_key
                          value: argo_server
                        - name: argo_auth_token_secret_name
                          value: sky-argo-secret
                        - name: argo_auth_token_secret_key
                          value: argo_auth_token
                    dependencies: [promote-frontend]