apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipper
  namespace: sky
  labels:
    app: flipper
spec:
  selector:
    matchLabels:
      app: flipper
  replicas: 6
  template:
    metadata:
      labels:
        app: flipper
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: flipper
        image: registry.flou.dev/sky-flipper:d3e51495-1cab-46c8-9f8e-1c3db5eccc70
        ports:
        - containerPort: 80
          name: web
        env: 
        - name: DBConnection
          valueFrom:
            secretKeyRef:
              name: secret 
              key: connection_read_secondary
        - name: SKYCOMMANDS_HOST
          value: "sky-commands-main-service:8008"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: jaeger_agent_host
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: kafka_host
        - name: REDIS_HOST
          valueFrom: 
            configMapKeyRef:
              name: config
              key: redis_host
        - name: TOPICS__FLIP
          valueFrom:
            configMapKeyRef:
              name: config
              key: topic_flip
        - name: TOPICS__NEW_AUCTION
          valueFrom:
            configMapKeyRef:
              name: config
              key: topic_new_auction
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flipper
  namespace: sky
spec:
  selector:
    app: flipper
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flipper-metrics-service
  namespace: sky
  labels:
    app: flipper-metrics-service
spec:
  selector:
    app: flipper
  ports:
  - port: 80
    targetPort: 80
    name: metrics
    protocol: TCP
