apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-connect
  namespace: sky
  labels:
    app: mc-connect
spec:
  selector:
    matchLabels:
      app: mc-connect
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-connect
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mc-connect
        image: registry.flou.dev/sky-mc-connect:458d9a6c-f2d5-4d7d-8238-952151c8b47d
        ports:
        - containerPort: 80
          name: web
        env: 
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: secret 
              key: connection_micro_mc_connect
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: kafka_host
        - name: TOPICS__NEW_AUCTION
          valueFrom:
            configMapKeyRef:
              name: config
              key: topic_new_auction
        - name: TOPICS__NEW_BID
          valueFrom:
            configMapKeyRef:
              name: config
              key: topic_new_bid
        - name: JAEGER_SERVICE_NAME
          value: sky-mc-connect
        - name: JAEGER_AGENT_HOST
          valueFrom: 
            configMapKeyRef:
              name: config
              key: jaeger_agent_host
---
apiVersion: v1
kind: Service
metadata:
  name: mc-connect
  namespace: sky
spec:
  selector:
    app: mc-connect
  ports:
  - port: 80
    targetPort: 80