apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: light-client
  namespace: sky
  labels:
    app: light-client
spec:
  revisionHistoryLimit: 5
  replicas: 5
  progressDeadlineSeconds: 2592000
  selector:
    matchLabels:
      app: light-client
  template:
    metadata:
      labels:
        app: light-client
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: light-client
        image: registry.flou.dev/sky:4be97f7b-9ac5-45e3-90ec-b891b5638791
        ports:
          - containerPort: 8008
          - containerPort: 80
        env:
          - name: TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                key: token_secret
                name: secret
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection_live
                name: secret
          - name: redisCon
            value: redis-service
          - name: MODE
            value: light
          - name: FRONTEND_PROD
            value: frontend
          - name: FRONTEND_STAGING
            value: frontend-preview
          - name: JAEGER_SERVICE_NAME
            valueFrom: 
              configMapKeyRef:
                name: config
                key: jaeger_service_name
          - name: JAEGER_AGENT_HOST
            valueFrom: 
              configMapKeyRef:
                name: config
                key: jaeger_agent_host
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "700Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
  strategy:
    blueGreen:
      activeService: light-client-service
      previewService: light-client-preview-service
      autoPromotionEnabled: false
      previewReplicaCount: 1
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: light-client-service
  namespace: sky
spec:
  selector:
    app: light-client
  ports:
    - port: 8008
      targetPort: 8008
      name: "websocket"
    - port: 80
      targetPort: 80
      name: "asp"
---
apiVersion: v1
kind: Service
metadata:
  name: light-client-preview-service
  namespace: sky
spec:
  selector:
    app: light-client
  ports:
    - port: 8008
      targetPort: 8008
      name: "websocket"
    - port: 80
      targetPort: 80
      name: "asp"
---
apiVersion: v1
kind: Service
metadata:
  name: light-client-metrics-service
  namespace: sky
  labels:
    app: light-client-metrics-service
spec:
  selector:
    app: light-client
  ports:
  - port: 80
    targetPort: 80
    name: metrics
    protocol: TCP
