apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sky-light-client-metrics-servicemonitor
  namespace: sky 
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: light-client-metrics-service
  endpoints:
  - port: metrics
    interval: 25s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sky-indexer-metrics-servicemonitor
  namespace: sky 
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: indexer-metrics-service
  endpoints:
  - port: metrics
    interval: 25s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: commands-metrics-servicemonitor
  namespace: sky 
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: commands-metrics-service
  endpoints:
  - port: metrics
    interval: 25s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: updater-metrics-servicemonitor
  namespace: sky 
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app:  updater-metrics-service
  endpoints:
  - port: metrics
    interval: 25s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flipper-metrics-servicemonitor
  namespace: sky 
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flipper-metrics-service
  endpoints:
  - port: metrics
    interval: 25s
    path: /metrics
