apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: updater
  namespace: sky
  labels:
    app: updater
spec:
  replicas: 3
  serviceName: updater
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: updater
  template:
    metadata:
      labels:
        app: updater
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: updater
        image: registry.flou.dev/sky-updater:c3bf6d5a-3626-49aa-89b5-189789df0818
        env:
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: token_secret
              name: secret
        - name: redisCon
          valueFrom:
            configMapKeyRef: 
              name: config
              key: redis_host
        - name: apiKey
          valueFrom:
            secretKeyRef:
              key: api
              name: secret
        - name: JAEGER_AGENT_HOST
          valueFrom: 
            configMapKeyRef:
              name: config
              key: jaeger_agent_host
        - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
          valueFrom:
            configMapKeyRef:
              name: config
              key: reload_config_on_change
        - name: TOPICS__MISSING_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_missing_auction-raw
        - name: TOPICS__SOLD_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_sold_auction-raw
        - name: TOPICS__NEW_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_new_auction-raw
        - name: TOPICS__AUCTION_ENDED
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_auction_ended-raw
        - name: TOPICS__NEW_BID
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_new_bid-raw
        - name: TOPICS__BAZAAR
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_bazaar-raw
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: kafka_host
        resources:
          requests:
            memory: "400Mi"
            cpu: "750m"
---
apiVersion: v1
kind: Service
metadata:
  name: updater
spec:
  selector:
    app: updater
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: updater-metrics-service
  namespace: sky
  labels:
    app: updater-metrics-service
spec:
  selector:
    app: updater
  ports:
  - port: 80
    targetPort: 80
    name: metrics
    protocol: TCP
