apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sky-eventsource
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    sky:
      port: "12000"
      endpoint: /sky
      method: POST
    sky-pull-request:
      port: "12000"
      endpoint: /sky-pull-request
      method: POST
    frontend:
      port: "12000"
      endpoint: /sky-frontend
      method: POST
    sky-core: 
      port: "12000"
      endpoint: /sky-core
      method: POST
    sky-commands: 
      port: "12000"
      endpoint: /sky-commands
      method: POST
    sky-subscriptions: 
      port: "12000"
      endpoint: /sky-subscriptions
      method: POST
    sky-flipper: 
      port: "12000"
      endpoint: /sky-flipper
      method: POST
    sky-mc-connect: 
      port: "12000"
      endpoint: /sky-mc-connect
      method: POST
    sky-filter: 
      port: "12000"
      endpoint: /sky-filter
      method: POST
    sky-stage-frontend: 
      port: "12000"
      endpoint: /sky-stage-frontend
    sky-updater: 
      port: "12000"
      endpoint: /sky-updater